SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `billing_simple` ;
CREATE SCHEMA IF NOT EXISTS `billing_simple` DEFAULT CHARACTER SET utf8 ;
USE `billing_simple` ;

-- -----------------------------------------------------
-- Table `billing_simple`.`billing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `billing_simple`.`billing` ;

CREATE TABLE IF NOT EXISTS `billing_simple`.`billing` (
  `payer_email` VARCHAR(255) NULL,
  `recipient_email` VARCHAR(255) NULL,
  `sum` DECIMAL(18,2) NULL,
  `currency` VARCHAR(3) NULL,
  `billing_date` DATE NULL,
  `comment` TEXT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `billing_simple`.`billing`
-- -----------------------------------------------------
START TRANSACTION;
USE `billing_simple`;
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('vasya@mail.com', 'petya@mail.com', 681.00, 'AUD', '13.12.2015', 'Procrastinator? No, I just wait until the last second to do my work because I will be older, therefore wiser.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('petya@mail.com', 'ivan@mail.com', 714.00, 'EUR', '22.12.2015', 'You remind me of my Chinese friend...Ug Lee.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('ivan@mail.com', 'bobby@mail.com', 338.00, 'SGD', '14.01.2015', 'I just dropped my laptop off the boat.....It\'s a Dell, rolling in the deep.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('bobby@mail.com', 'lenny@mail.com', 157.00, 'INR', '17.06.2015', 'I was planning to do something today, but I haven\'t finished doing nothing from yesterday.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('lenny@mail.com', 'alex@mail.com', 623.00, 'CHF', '04.01.2015', 'I just dropped my laptop off the boat.....It\'s a Dell, rolling in the deep.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('alex@mail.com', 'john@mail.com', 722.00, 'EUR', '02.09.2015', 'I feel like getting something done today, so I\'m just going to sit here until the feeling passes.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('john@mail.com', 'leo@mail.com', 198.00, 'JPY', '19.08.2015', 'Whatever you do in life give 100%.....unless you\'re giving blood.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('leo@mail.com', 'enzo@mail.com', 240.00, 'MYR', '20.06.2015', 'I was complimented on my driving. Someone left a note on my windshield that said, \'Parking Fine.\'');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('enzo@mail.com', 'franz@mail.com', 647.00, 'JPY', '08.03.2015', 'I was complimented on my driving. Someone left a note on my windshield that said, \'Parking Fine.\'');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('franz@mail.com', 'vasya@mail.com', 960.00, 'CHF', '09.07.2015', 'I really like ceilings......I guess you could call me a ceiling fan.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('vasya@mail.com', 'ivan@mail.com', 141.00, 'MYR', '26.11.2015', 'I was complimented on my driving. Someone left a note on my windshield that said, \'Parking Fine.\'');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('petya@mail.com', 'bobby@mail.com', 776.00, 'JPY', '29.05.2015', 'I was planning to do something today, but I haven\'t finished doing nothing from yesterday.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('ivan@mail.com', 'lenny@mail.com', 546.00, 'INR', '18.09.2015', 'Grammar is somewhat important. Commas do save lives for instance: \'Let\'s eat grandpa.\' \'Lets eat, grandpa.\'');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('bobby@mail.com', 'alex@mail.com', 251.00, 'CAD', '21.01.2015', 'I feel like getting something done today, so I\'m just going to sit here until the feeling passes.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('lenny@mail.com', 'john@mail.com', 646.00, 'CHF', '13.01.2015', 'Whatever you do in life give 100%.....unless you\'re giving blood.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('alex@mail.com', 'leo@mail.com', 997.00, 'MYR', '10.08.2015', 'Better late then never, but never late is better.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('john@mail.com', 'enzo@mail.com', 261.00, 'AUD', '27.12.2015', 'I speak my mind. I never mind what I speak.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('leo@mail.com', 'franz@mail.com', 687.00, 'INR', '19.01.2015', 'Procrastinator? No, I just wait until the last second to do my work because I will be older, therefore wiser.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('enzo@mail.com', 'vasya@mail.com', 211.00, 'AUD', '23.05.2015', 'Grammar is somewhat important. Commas do save lives for instance: \'Let\'s eat grandpa.\' \'Lets eat, grandpa.\'');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('franz@mail.com', 'petya@mail.com', 352.00, 'SGD', '04.06.2015', 'Better late then never, but never late is better.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('vasya@mail.com', 'bobby@mail.com', 930.00, 'GBP', '09.01.2015', 'Whatever you do in life give 100%.....unless you\'re giving blood.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('petya@mail.com', 'lenny@mail.com', 639.00, 'EUR', '14.09.2015', 'I haven\'t seen any statuses about Ninjas lately....well played Ninjas.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('ivan@mail.com', 'alex@mail.com', 142.00, 'SGD', '26.07.2015', 'On a scale of Voldemort to Pinocchio, how Nosy are you?');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('bobby@mail.com', 'john@mail.com', 276.00, 'SGD', '18.10.2015', 'I changed all my passwords to \'incorrect\'. So my computer just tells me when I forgot.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('lenny@mail.com', 'leo@mail.com', 258.00, 'CAD', '21.05.2015', 'Better late then never, but never late is better.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('alex@mail.com', 'enzo@mail.com', 109.00, 'USD', '03.09.2015', 'The dictionary is the only place where success comes before work.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('john@mail.com', 'franz@mail.com', 799.00, 'SGD', '20.04.2015', 'I just dropped my laptop off the boat.....It\'s a Dell, rolling in the deep.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('leo@mail.com', 'vasya@mail.com', 759.00, 'EUR', '14.04.2015', 'I wish real life was like cartoons. I could wear the same outfit and nobody would care.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('enzo@mail.com', 'petya@mail.com', 412.00, 'AUD', '25.01.2015', 'I haven\'t seen any statuses about Ninjas lately....well played Ninjas.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('franz@mail.com', 'ivan@mail.com', 394.00, 'GBP', '07.09.2015', 'I wish real life was like cartoons. I could wear the same outfit and nobody would care.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('vasya@mail.com', 'lenny@mail.com', 300.00, 'EUR', '09.05.2015', 'I love how, in horror movies, the person yells out,Hello? As if the bad is going to yell back, Yeah, I\'m in the kitchen! Do you want a sandwich? Or,Hey, yeah I\'m back here with a chainsaw. Come on down.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('petya@mail.com', 'alex@mail.com', 800.00, 'USD', '01.01.2015', 'I do 5 sit-ups every morning. May not sound like much, but there is only so many times you can hit the snooze button...\'');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('ivan@mail.com', 'john@mail.com', 429.00, 'CAD', '03.09.2015', 'I dream of a better tomorrow, where chickens can cross the road and not be questioned about their motives.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('bobby@mail.com', 'leo@mail.com', 580.00, 'GBP', '16.09.2015', 'I wish real life was like cartoons. I could wear the same outfit and nobody would care.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('lenny@mail.com', 'enzo@mail.com', 335.00, 'CAD', '24.03.2015', 'One time at the beach this guy was swimming in the ocean yelling Help! Shark! Help!. I just laughed, I knew that shark wasn\'t going to help them.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('alex@mail.com', 'franz@mail.com', 610.00, 'JPY', '14.06.2015', 'I wish real life was like cartoons. I could wear the same outfit and nobody would care.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('john@mail.com', 'vasya@mail.com', 356.00, 'MYR', '12.11.2015', 'I feel like getting something done today, so I\'m just going to sit here until the feeling passes.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('leo@mail.com', 'petya@mail.com', 993.00, 'JPY', '30.03.2015', 'I changed all my passwords to \'incorrect\'. So my computer just tells me when I forgot.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('enzo@mail.com', 'ivan@mail.com', 824.00, 'GBP', '28.08.2015', 'I was planning to do something today, but I haven\'t finished doing nothing from yesterday.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('franz@mail.com', 'bobby@mail.com', 422.00, 'EUR', '04.05.2015', 'No I didn\'t trip, the floor looked like it needed a hug.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('vasya@mail.com', 'alex@mail.com', 845.00, 'CAD', '11.04.2015', 'The dictionary is the only place where success comes before work.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('petya@mail.com', 'john@mail.com', 925.00, 'USD', '09.07.2015', 'Grammar is somewhat important. Commas do save lives for instance: \'Let\'s eat grandpa.\' \'Lets eat, grandpa.\'');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('ivan@mail.com', 'leo@mail.com', 185.00, 'EUR', '21.08.2015', 'I just dropped my laptop off the boat.....It\'s a Dell, rolling in the deep.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('bobby@mail.com', 'enzo@mail.com', 245.00, 'GBP', '20.02.2015', 'I wish real life was like cartoons. I could wear the same outfit and nobody would care.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('lenny@mail.com', 'franz@mail.com', 533.00, 'GBP', '16.01.2015', 'You remind me of my Chinese friend...Ug Lee.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('alex@mail.com', 'vasya@mail.com', 502.00, 'AUD', '28.10.2015', 'I was complimented on my driving. Someone left a note on my windshield that said, \'Parking Fine.\'');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('john@mail.com', 'petya@mail.com', 110.00, 'EUR', '10.05.2015', 'I changed all my passwords to \'incorrect\'. So my computer just tells me when I forgot.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('leo@mail.com', 'ivan@mail.com', 223.00, 'GBP', '01.08.2015', 'Grammar is somewhat important. Commas do save lives for instance: \'Let\'s eat grandpa.\' \'Lets eat, grandpa.\'');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('enzo@mail.com', 'bobby@mail.com', 177.00, 'USD', '16.03.2015', 'I speak my mind. I never mind what I speak.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('franz@mail.com', 'lenny@mail.com', 839.00, 'USD', '06.11.2015', 'I dream of a better tomorrow, where chickens can cross the road and not be questioned about their motives.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('vasya@mail.com', 'john@mail.com', 942.00, 'CHF', '07.12.2015', 'Better late then never, but never late is better.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('petya@mail.com', 'leo@mail.com', 102.00, 'GBP', '15.02.2015', 'I do 5 sit-ups every morning. May not sound like much, but there is only so many times you can hit the snooze button...\'');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('ivan@mail.com', 'enzo@mail.com', 711.00, 'AUD', '29.05.2015', 'I speak my mind. I never mind what I speak.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('bobby@mail.com', 'franz@mail.com', 624.00, 'USD', '08.01.2015', 'I love how, in horror movies, the person yells out,Hello? As if the bad is going to yell back, Yeah, I\'m in the kitchen! Do you want a sandwich? Or,Hey, yeah I\'m back here with a chainsaw. Come on down.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('lenny@mail.com', 'vasya@mail.com', 698.00, 'USD', '26.02.2015', 'I wonder if tap dancers walk into a room, look at the floor and think,\'I\'d so tap that.\'');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('alex@mail.com', 'petya@mail.com', 843.00, 'MYR', '14.02.2015', 'I wonder if tap dancers walk into a room, look at the floor and think,\'I\'d so tap that.\'');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('john@mail.com', 'ivan@mail.com', 808.00, 'EUR', '21.09.2015', 'I wonder if tap dancers walk into a room, look at the floor and think,\'I\'d so tap that.\'');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('leo@mail.com', 'bobby@mail.com', 527.00, 'AUD', '09.08.2015', 'I wish real life was like cartoons. I could wear the same outfit and nobody would care.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('enzo@mail.com', 'lenny@mail.com', 585.00, 'CHF', '06.09.2015', 'You remind me of my Chinese friend...Ug Lee.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('franz@mail.com', 'alex@mail.com', 808.00, 'CAD', '07.06.2015', 'One time at the beach this guy was swimming in the ocean yelling Help! Shark! Help!. I just laughed, I knew that shark wasn\'t going to help them.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('vasya@mail.com', 'leo@mail.com', 349.00, 'USD', '07.10.2015', 'I was complimented on my driving. Someone left a note on my windshield that said, \'Parking Fine.\'');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('petya@mail.com', 'enzo@mail.com', 265.00, 'INR', '29.06.2015', 'I dream of a better tomorrow, where chickens can cross the road and not be questioned about their motives.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('ivan@mail.com', 'franz@mail.com', 180.00, 'SGD', '15.03.2015', 'I was planning to do something today, but I haven\'t finished doing nothing from yesterday.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('bobby@mail.com', 'vasya@mail.com', 129.00, 'USD', '06.10.2015', 'You remind me of my Chinese friend...Ug Lee.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('lenny@mail.com', 'petya@mail.com', 703.00, 'SGD', '31.03.2015', 'I haven\'t seen any statuses about Ninjas lately....well played Ninjas.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('alex@mail.com', 'ivan@mail.com', 533.00, 'EUR', '04.02.2015', 'Procrastinator? No, I just wait until the last second to do my work because I will be older, therefore wiser.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('john@mail.com', 'bobby@mail.com', 129.00, 'SGD', '31.10.2015', 'On a scale of Voldemort to Pinocchio, how Nosy are you?');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('leo@mail.com', 'lenny@mail.com', 858.00, 'MYR', '14.04.2015', 'I changed all my passwords to \'incorrect\'. So my computer just tells me when I forgot.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('enzo@mail.com', 'alex@mail.com', 461.00, 'JPY', '09.08.2015', 'Grammar is somewhat important. Commas do save lives for instance: \'Let\'s eat grandpa.\' \'Lets eat, grandpa.\'');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('franz@mail.com', 'john@mail.com', 467.00, 'CAD', '07.01.2015', 'I wonder if tap dancers walk into a room, look at the floor and think,\'I\'d so tap that.\'');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('vasya@mail.com', 'enzo@mail.com', 684.00, 'USD', '07.05.2015', 'No I didn\'t trip, the floor looked like it needed a hug.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('petya@mail.com', 'franz@mail.com', 329.00, 'CHF', '28.01.2015', 'Grammar is somewhat important. Commas do save lives for instance: \'Let\'s eat grandpa.\' \'Lets eat, grandpa.\'');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('ivan@mail.com', 'vasya@mail.com', 823.00, 'JPY', '18.12.2015', 'I just dropped my laptop off the boat.....It\'s a Dell, rolling in the deep.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('bobby@mail.com', 'petya@mail.com', 377.00, 'CHF', '20.07.2015', 'Whatever you do in life give 100%.....unless you\'re giving blood.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('lenny@mail.com', 'ivan@mail.com', 604.00, 'GBP', '17.04.2015', 'I haven\'t seen any statuses about Ninjas lately....well played Ninjas.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('alex@mail.com', 'bobby@mail.com', 979.00, 'GBP', '15.04.2015', 'One time at the beach this guy was swimming in the ocean yelling Help! Shark! Help!. I just laughed, I knew that shark wasn\'t going to help them.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('john@mail.com', 'lenny@mail.com', 683.00, 'JPY', '15.05.2015', 'One time at the beach this guy was swimming in the ocean yelling Help! Shark! Help!. I just laughed, I knew that shark wasn\'t going to help them.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('leo@mail.com', 'alex@mail.com', 611.00, 'SGD', '27.06.2015', 'I do 5 sit-ups every morning. May not sound like much, but there is only so many times you can hit the snooze button...\'');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('enzo@mail.com', 'john@mail.com', 761.00, 'AUD', '02.08.2015', 'I changed all my passwords to \'incorrect\'. So my computer just tells me when I forgot.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('franz@mail.com', 'leo@mail.com', 587.00, 'CAD', '24.10.2015', 'I love how, in horror movies, the person yells out,Hello? As if the bad is going to yell back, Yeah, I\'m in the kitchen! Do you want a sandwich? Or,Hey, yeah I\'m back here with a chainsaw. Come on down.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('vasya@mail.com', 'franz@mail.com', 666.00, 'GBP', '03.04.2015', 'Better late then never, but never late is better.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('petya@mail.com', 'vasya@mail.com', 792.00, 'AUD', '21.01.2015', 'I do 5 sit-ups every morning. May not sound like much, but there is only so many times you can hit the snooze button...\'');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('ivan@mail.com', 'petya@mail.com', 521.00, 'MYR', '23.02.2015', 'On a scale of Voldemort to Pinocchio, how Nosy are you?');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('bobby@mail.com', 'ivan@mail.com', 788.00, 'SGD', '05.10.2015', 'Whatever you do in life give 100%.....unless you\'re giving blood.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('lenny@mail.com', 'bobby@mail.com', 491.00, 'INR', '04.02.2015', 'I was planning to do something today, but I haven\'t finished doing nothing from yesterday.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('alex@mail.com', 'lenny@mail.com', 247.00, 'EUR', '10.10.2015', 'I really like ceilings......I guess you could call me a ceiling fan.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('john@mail.com', 'alex@mail.com', 137.00, 'CHF', '04.06.2015', 'I speak my mind. I never mind what I speak.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('leo@mail.com', 'john@mail.com', 514.00, 'GBP', '16.12.2015', 'I love how, in horror movies, the person yells out,Hello? As if the bad is going to yell back, Yeah, I\'m in the kitchen! Do you want a sandwich? Or,Hey, yeah I\'m back here with a chainsaw. Come on down.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('enzo@mail.com', 'leo@mail.com', 990.00, 'INR', '01.09.2015', 'I dream of a better tomorrow, where chickens can cross the road and not be questioned about their motives.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('franz@mail.com', 'enzo@mail.com', 459.00, 'CHF', '15.09.2015', 'Anytime a bird poops on one of my windows, I eat a whole plate of scrambled egg on my patio. Just to show them what I\'m capable of. Take that birds');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('vasya@mail.com', 'petya@mail.com', 120.00, 'INR', '31.08.2015', 'Anytime a bird poops on one of my windows, I eat a whole plate of scrambled egg on my patio. Just to show them what I\'m capable of. Take that birds');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('petya@mail.com', 'ivan@mail.com', 610.00, 'GBP', '13.01.2015', 'I do 5 sit-ups every morning. May not sound like much, but there is only so many times you can hit the snooze button...\'');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('ivan@mail.com', 'bobby@mail.com', 466.00, 'CHF', '16.05.2015', 'One time at the beach this guy was swimming in the ocean yelling Help! Shark! Help!. I just laughed, I knew that shark wasn\'t going to help them.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('bobby@mail.com', 'lenny@mail.com', 275.00, 'CHF', '11.08.2015', 'I was planning to do something today, but I haven\'t finished doing nothing from yesterday.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('lenny@mail.com', 'alex@mail.com', 104.00, 'CHF', '22.12.2015', 'You remind me of my Chinese friend...Ug Lee.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('alex@mail.com', 'john@mail.com', 308.00, 'EUR', '19.01.2015', 'I was planning to do something today, but I haven\'t finished doing nothing from yesterday.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('john@mail.com', 'leo@mail.com', 257.00, 'AUD', '07.08.2015', 'I changed all my passwords to \'incorrect\'. So my computer just tells me when I forgot.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('leo@mail.com', 'enzo@mail.com', 477.00, 'MYR', '20.10.2015', 'One time at the beach this guy was swimming in the ocean yelling Help! Shark! Help!. I just laughed, I knew that shark wasn\'t going to help them.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('enzo@mail.com', 'franz@mail.com', 436.00, 'USD', '07.04.2015', 'The dictionary is the only place where success comes before work.');
INSERT INTO `billing_simple`.`billing` (`payer_email`, `recipient_email`, `sum`, `currency`, `billing_date`, `comment`) VALUES ('franz@mail.com', 'vasya@mail.com', 398.00, 'GBP', '30.07.2015', 'I wish real life was like cartoons. I could wear the same outfit and nobody would care.');

COMMIT;

